name: Format & Test Checks

on: [push]

jobs:
    type-checks:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: "npm"
            - run: npm ci
            - run: npm run type-checks
    format-checks:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: "npm"
            - run: npm ci
            - run: npm run lint
    unit-tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: "npm"
            - run: npm ci
            - run: npm run test:unit
    e2e-tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: supabase/setup-cli@v1
              with:
                  version: latest
            - run: supabase start
            - run: supabase status
            - uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: "npm"
            - run: npm ci
            - run: npm run build
            - name: E2E Tests
              run: npm run test:e2e
              env:
                  # Local values
                  NEXT_PUBLIC_URL: http://localhost:3000
                  SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
                  SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
                  SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
            - uses: actions/upload-artifact@v4
              if: ${{ !cancelled() }}
              with:
                  name: playwright-report
                  path: playwright-report/
                  retention-days: 7
