name: Format & Test Checks

on: [push]

jobs:
    type-checks:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: "npm"
            - run: npm ci
            - run: npm run type-checks
    format-checks:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: "npm"
            - run: npm ci
            - run: npm run lint
    unit-tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: "npm"
            - run: npm ci
            - run: npm run test:unit
# Disabled E2E action because it took up lots of GitHub Action minutes as each run took approx 10 minute.
#    e2e-tests:
#        runs-on: ubuntu-latest
#        steps:
#            - uses: actions/checkout@v4
#            # Setup Supabase CLI
#            - uses: supabase/setup-cli@v1
#              with:
#                  version: latest
#            - run: supabase start
#            - run: supabase status
#            # Setup Node.js environment
#            - uses: actions/setup-node@v4
#              with:
#                  node-version: "20"
#                  cache: "npm"
#            # Install dependencies and build
#            - run: npm ci
#            - run: npx playwright install --with-deps chromium
#            - name: Build Website
#              run: npm run build
#              env:
#                  NEXT_PUBLIC_URL: http://localhost:3000
#                  SUPABASE_URL: ${{ vars.SUPABASE_URL }}
#                  NEXT_PUBLIC_SUPABASE_URL: ${{ vars.SUPABASE_URL }}
#                  SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
#                  NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
#                  SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
#                  RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
#            # Run E2E Tests
#            - name: E2E Tests
#              run: npm run test:e2e
#              env:
#                  NEXT_PUBLIC_URL: http://localhost:3000
#                  SUPABASE_URL: ${{ vars.SUPABASE_URL }}
#                  NEXT_PUBLIC_SUPABASE_URL: ${{ vars.SUPABASE_URL }}
#                  SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
#                  NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
#                  SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
#                  RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
#            # Upload Playwright report as an artifact
#            - uses: actions/upload-artifact@v4
#              if: ${{ !cancelled() }}
#              with:
#                  name: playwright-report
#                  path: playwright-report/
#                  retention-days: 7
