name: Format & Test Checks

on: [push]

jobs:
    type-checks:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: "npm"
            - run: npm ci
            - run: npm run type-checks
    format-checks:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: "npm"
            - run: npm ci
            - run: npm run lint
    unit-tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: "npm"
            - run: npm ci
            - run: npm run test:unit
    e2e-tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            # Cache Supabase Docker images to speed up `supabase start`
            - name: Cache Supabase Docker images
              uses: actions/cache@v3
              with:
                  path: /tmp/.docker-cache
                  key: ${{ runner.os }}-docker-supabase-${{ hashFiles('**/Dockerfile') }}
                  restore-keys: |
                      ${{ runner.os }}-docker-supabase-

            # Pre-pull the Supabase-related Docker images
            - name: Pre-pull Supabase Docker Images
              run: |
                  export DOCKER_CACHE_DIR=/tmp/.docker-cache
                  docker pull supabase/postgres:latest
                  docker pull supabase/storage:latest
                  docker pull supabase/realtime:latest
                  docker pull supabase/imgproxy:latest
                  docker pull supabase/gotrue:latest
                  docker pull supabase/rest:latest

            # Setup Supabase CLI
            - uses: supabase/setup-cli@v1
              with:
                  version: latest

            # Start Supabase (should use cached images if available)
            - run: supabase start
            - run: supabase status

            # Setup Node.js environment
            - uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: "npm"

            # Install dependencies and build
            - run: npm ci
            - run: npm run build

            # Run E2E Tests
            - name: E2E Tests
              run: npm run test:e2e
              env:
                  NEXT_PUBLIC_URL: http://localhost:3000
                  SUPABASE_URL: ${{ vars.SUPABASE_URL }}
                  SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
                  SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
                  RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}

            # Upload Playwright report as an artifact
            - uses: actions/upload-artifact@v4
              if: ${{ !cancelled() }}
              with:
                  name: playwright-report
                  path: playwright-report/
                  retention-days: 7